begin;

alter table public.profiles
  add column if not exists needs_rematch boolean not null default true,
  add column if not exists last_matched_at timestamptz;

create index if not exists idx_profiles_needs_rematch on public.profiles(needs_rematch);

create table if not exists public.university_stats (
  id bigint generated by default as identity primary key,
  university_id bigint not null unique references public.universities(id) on delete cascade,
  total_applications integer not null default 0,
  total_offers integer not null default 0,
  total_visas integer not null default 0,
  acceptance_rate numeric(5,2),
  visa_success_rate numeric(5,2),
  avg_processing_time integer,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_university_stats_university_id on public.university_stats(university_id);

drop trigger if exists trg_university_stats_updated_at on public.university_stats;
create trigger trg_university_stats_updated_at
before update on public.university_stats
for each row execute function public.set_updated_at();

alter table public.university_stats enable row level security;

create policy "Public read university stats"
on public.university_stats
for select
to anon, authenticated
using (true);

create policy "Admin manage university stats"
on public.university_stats
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

commit;
