begin;

alter table public.profiles
  add column if not exists counselor_active boolean not null default true;

create table if not exists public.notes (
  id bigint generated by default as identity primary key,
  student_user_id uuid not null references auth.users(id) on delete cascade,
  author_user_id uuid not null references auth.users(id) on delete cascade,
  author_role text not null check (author_role in ('admin', 'counselor')),
  note text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_notes_student_user_id on public.notes(student_user_id);
create index if not exists idx_notes_author_user_id on public.notes(author_user_id);

drop trigger if exists trg_notes_updated_at on public.notes;
create trigger trg_notes_updated_at
before update on public.notes
for each row execute function public.set_updated_at();

alter table public.notes enable row level security;

create or replace function public.is_counselor()
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (
    select 1
    from public.profiles
    where user_id = auth.uid()
      and role = 'counselor'
  );
$$;

revoke all on function public.is_counselor() from public;
grant execute on function public.is_counselor() to authenticated;

create or replace function public.is_assigned_counselor(student_user uuid)
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (
    select 1
    from public.profiles
    where user_id = student_user
      and assigned_counselor_id = auth.uid()
      and role = 'student'
  );
$$;

revoke all on function public.is_assigned_counselor(uuid) from public;
grant execute on function public.is_assigned_counselor(uuid) to authenticated;

drop policy if exists "Profiles select own or admin" on public.profiles;
create policy "Profiles select own or admin"
on public.profiles
for select
to authenticated
using (
  auth.uid() = user_id
  or public.is_admin()
  or (
    public.is_counselor()
    and role = 'student'
    and assigned_counselor_id = auth.uid()
  )
);

drop policy if exists "Applications select own or admin" on public.applications;
create policy "Applications select own or admin"
on public.applications
for select
to authenticated
using (auth.uid() = user_id or public.is_admin() or (public.is_counselor() and counselor_id = auth.uid()));

drop policy if exists "Applications update own or admin" on public.applications;
create policy "Applications update own or admin"
on public.applications
for update
to authenticated
using (auth.uid() = user_id or public.is_admin() or (public.is_counselor() and counselor_id = auth.uid()))
with check (auth.uid() = user_id or public.is_admin() or (public.is_counselor() and counselor_id = auth.uid()));

drop policy if exists "Documents select own or admin" on public.documents;
create policy "Documents select own or admin"
on public.documents
for select
to authenticated
using (auth.uid() = user_id or public.is_admin() or (public.is_counselor() and public.is_assigned_counselor(user_id)));

drop policy if exists "Notes select staff" on public.notes;
create policy "Notes select staff"
on public.notes
for select
to authenticated
using (
  public.is_admin()
  or auth.uid() = author_user_id
  or (public.is_counselor() and public.is_assigned_counselor(student_user_id))
);

drop policy if exists "Notes insert staff" on public.notes;
create policy "Notes insert staff"
on public.notes
for insert
to authenticated
with check (
  public.is_admin()
  or (
    public.is_counselor()
    and auth.uid() = author_user_id
    and public.is_assigned_counselor(student_user_id)
  )
);

commit;
