-- Notifications table for StudyGlobal
-- Run this in the Supabase SQL Editor after schema_full.sql

begin;

create table if not exists public.notifications (
  id          bigint generated by default as identity primary key,
  user_id     uuid not null references auth.users(id) on delete cascade,
  type        text not null default 'info' check (type in ('info', 'success', 'warning', 'error')),
  title       text not null,
  message     text,
  read        boolean not null default false,
  link        text,
  created_at  timestamptz not null default now()
);

create index if not exists notifications_user_id_idx on public.notifications(user_id);
create index if not exists notifications_read_idx    on public.notifications(user_id, read);

alter table public.notifications enable row level security;

-- Users can only see their own notifications
create policy "notifications_select_own"
  on public.notifications for select
  to authenticated
  using (auth.uid() = user_id);

-- Users can update (mark read) their own notifications
create policy "notifications_update_own"
  on public.notifications for update
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- Users can delete their own notifications
create policy "notifications_delete_own"
  on public.notifications for delete
  to authenticated
  using (auth.uid() = user_id);

-- Only service role / admin functions can insert notifications
create policy "notifications_insert_admin"
  on public.notifications for insert
  to authenticated
  with check (public.is_admin() or auth.uid() = user_id);

-- Enable real-time for this table
alter publication supabase_realtime add table public.notifications;

commit;

-- ──────────────────────────────────────────────────────────────────────────
-- Helper function: send a notification to a user
-- Call from database triggers or edge functions:
--   select notify_user('<user_uuid>', 'info', 'Title here', 'Optional body', '/optional/link');
-- ──────────────────────────────────────────────────────────────────────────
create or replace function public.notify_user(
  p_user_id uuid,
  p_type    text,
  p_title   text,
  p_message text default null,
  p_link    text default null
)
returns void
language plpgsql
security definer
as $$
begin
  insert into public.notifications(user_id, type, title, message, link)
  values (p_user_id, p_type, p_title, p_message, p_link);
end;
$$;
