-- StudyGlobal complete Supabase schema bootstrap
-- Run this in the Supabase SQL editor with a service-role connection.
-- It is intended to be idempotent and to cover the tables/policies the app code expects.

begin;

create extension if not exists pgcrypto;
create extension if not exists pg_trgm;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.profiles (
  id bigint generated by default as identity primary key,
  user_id uuid not null unique references auth.users(id) on delete cascade,
  name text not null,
  email text not null,
  profile_picture_url text,
  phone text,
  nationality text,
  preferred_country text,
  education_level text,
  gpa numeric(3,2),
  gpa_scale numeric(4,2),
  academic_system text,
  english_score numeric(4,1),
  english_test_type text,
  medium_of_instruction text,
  last_education_year integer,
  study_level text,
  preferred_subject text,
  preferred_intake_name text,
  preferred_intake_year integer,
  budget_min integer,
  budget_max integer,
  intake text,
  role text not null default 'student' check (role in ('student', 'admin', 'counselor', 'editor')),
  profile_completion integer not null default 0 check (profile_completion between 0 and 100),
  profile_status text not null default 'incomplete' check (profile_status in ('complete', 'incomplete')),
  lead_score integer not null default 0,
  lead_temperature text not null default 'Cold Lead' check (lead_temperature in ('Hot Lead', 'Warm Lead', 'Cold Lead')),
  duplicate_flags jsonb not null default '[]'::jsonb,
  fraud_flags jsonb not null default '[]'::jsonb,
  visa_risk_score integer not null default 0,
  visa_risk_level text not null default 'Medium risk' check (visa_risk_level in ('Low risk', 'Medium risk', 'High risk')),
  needs_rematch boolean not null default true,
  last_matched_at timestamptz,
  counselor_specializations jsonb not null default '[]'::jsonb,
  counselor_capacity integer not null default 30,
  counselor_active boolean not null default true,
  assigned_counselor_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.countries (
  id bigint generated by default as identity primary key,
  name text not null unique,
  description text,
  flag_emoji text,
  image_url text,
  university_count integer default 0,
  avg_tuition integer,
  min_gpa_required numeric(3,2),
  gpa_tolerance numeric(3,2),
  english_test_required boolean default true,
  english_medium_waiver_allowed boolean default true,
  max_gap_years integer,
  gap_risk_threshold integer,
  budget_tolerance_pct numeric(4,2),
  doc_requirements jsonb default '[]'::jsonb,
  requirements jsonb default '{}'::jsonb,
  intl_students text,
  popular_cities text,
  highlights text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.universities (
  id bigint generated by default as identity primary key,
  name text not null unique,
  country text not null,
  description text,
  ranking integer,
  logo_url text,
  tuition_min integer,
  tuition_max integer,
  acceptance_rate numeric(5,2),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.university_stats (
  id bigint generated by default as identity primary key,
  university_id bigint not null unique references public.universities(id) on delete cascade,
  total_applications integer not null default 0,
  total_offers integer not null default 0,
  total_visas integer not null default 0,
  acceptance_rate numeric(5,2),
  visa_success_rate numeric(5,2),
  avg_processing_time integer,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.programs (
  id bigint generated by default as identity primary key,
  university_id bigint not null references public.universities(id) on delete cascade,
  name text not null,
  degree_level text not null,
  duration text,
  tuition_fee integer,
  subject_area text,
  related_subjects jsonb default '[]'::jsonb,
  min_gpa_required numeric(3,2),
  min_english_score numeric(4,1),
  english_test_required boolean,
  intakes jsonb not null default '[]'::jsonb,
  intake_periods text,
  scholarship_available boolean not null default false,
  application_deadline timestamptz,
  scholarship_deadline timestamptz,
  seats_total integer,
  seats_filled integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.scholarships (
  id bigint generated by default as identity primary key,
  name text not null,
  university_id bigint references public.universities(id) on delete cascade,
  program_id bigint references public.programs(id) on delete set null,
  funding_type text,
  amount integer,
  description text,
  eligibility text,
  min_gpa_required numeric(3,2),
  deadline timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.blog_posts (
  id bigint generated by default as identity primary key,
  title text not null,
  slug text not null unique,
  excerpt text,
  content text,
  image_url text,
  category text,
  published boolean not null default false,
  author_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.applications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  program_id bigint not null references public.programs(id) on delete cascade,
  counselor_id uuid references auth.users(id) on delete set null,
  intake text,
  notes text,
  eligibility_snapshot jsonb default '{}'::jsonb,
  risk_snapshot jsonb default '{}'::jsonb,
  timeline jsonb not null default '[]'::jsonb,
  deadline_snapshot jsonb default '{}'::jsonb,
  next_steps jsonb not null default '[]'::jsonb,
  offer_type text check (offer_type in ('conditional', 'unconditional')),
  offer_received_at timestamptz,
  offer_letter_file_url text,
  admin_override boolean not null default false,
  override_reason text,
  status text not null default 'draft' check (
    status in ('draft', 'submitted', 'under_review', 'accepted', 'rejected', 'visa_processing')
  ),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.documents (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  document_type text not null,
  file_name text not null,
  file_url text not null,
  file_size bigint,
  quality_flag text,
  quality_flags jsonb not null default '[]'::jsonb,
  mime_type text,
  review_notes text,
  rejection_reason text,
  status text not null default 'pending' check (status in ('pending', 'verified', 'rejected')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  actor_user_id uuid references auth.users(id) on delete set null,
  action text not null,
  entity_type text not null,
  entity_id text,
  details jsonb default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.notes (
  id bigint generated by default as identity primary key,
  student_user_id uuid not null references auth.users(id) on delete cascade,
  author_user_id uuid not null references auth.users(id) on delete cascade,
  author_role text not null check (author_role in ('admin', 'counselor')),
  note text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.profiles
  add column if not exists profile_picture_url text,
  add column if not exists gpa_scale numeric(4,2),
  add column if not exists academic_system text,
  add column if not exists medium_of_instruction text,
  add column if not exists last_education_year integer,
  add column if not exists preferred_intake_name text,
  add column if not exists preferred_intake_year integer,
  add column if not exists profile_status text not null default 'incomplete',
  add column if not exists lead_score integer not null default 0,
  add column if not exists lead_temperature text not null default 'Cold Lead',
  add column if not exists duplicate_flags jsonb not null default '[]'::jsonb,
  add column if not exists fraud_flags jsonb not null default '[]'::jsonb,
  add column if not exists visa_risk_score integer not null default 0,
  add column if not exists visa_risk_level text not null default 'Medium risk',
  add column if not exists needs_rematch boolean not null default true,
  add column if not exists last_matched_at timestamptz,
  add column if not exists counselor_specializations jsonb not null default '[]'::jsonb,
  add column if not exists counselor_capacity integer not null default 30,
  add column if not exists counselor_active boolean not null default true,
  add column if not exists assigned_counselor_id uuid references auth.users(id) on delete set null,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

alter table public.countries
  add column if not exists min_gpa_required numeric(3,2),
  add column if not exists gpa_tolerance numeric(3,2),
  add column if not exists english_test_required boolean default true,
  add column if not exists english_medium_waiver_allowed boolean default true,
  add column if not exists max_gap_years integer,
  add column if not exists gap_risk_threshold integer,
  add column if not exists budget_tolerance_pct numeric(4,2),
  add column if not exists doc_requirements jsonb default '[]'::jsonb,
  add column if not exists requirements jsonb default '{}'::jsonb,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

alter table public.universities
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

alter table public.university_stats
  add column if not exists total_applications integer not null default 0,
  add column if not exists total_offers integer not null default 0,
  add column if not exists total_visas integer not null default 0,
  add column if not exists acceptance_rate numeric(5,2),
  add column if not exists visa_success_rate numeric(5,2),
  add column if not exists avg_processing_time integer,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

alter table public.programs
  add column if not exists subject_area text,
  add column if not exists related_subjects jsonb default '[]'::jsonb,
  add column if not exists english_test_required boolean,
  add column if not exists intakes jsonb not null default '[]'::jsonb,
  add column if not exists application_deadline timestamptz,
  add column if not exists scholarship_deadline timestamptz,
  add column if not exists seats_total integer,
  add column if not exists seats_filled integer not null default 0,
  add column if not exists is_active boolean not null default true,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

alter table public.scholarships
  add column if not exists funding_percentage numeric(5,2),
  add column if not exists study_level text,
  add column if not exists intake text default 'Any',
  add column if not exists application_type text not null default 'manual',
  add column if not exists additional_requirements text,
  add column if not exists is_stackable boolean not null default false,
  add column if not exists merit_based boolean not null default true,
  add column if not exists need_based boolean not null default false,
  add column if not exists is_featured boolean not null default false,
  add column if not exists is_active boolean not null default true,
  add column if not exists min_english_score numeric(4,1),
  add column if not exists english_test_type text,
  add column if not exists gpa_tolerance numeric(3,2) default 0.2,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

alter table public.blog_posts
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

alter table public.applications
  add column if not exists eligibility_snapshot jsonb default '{}'::jsonb,
  add column if not exists risk_snapshot jsonb default '{}'::jsonb,
  add column if not exists timeline jsonb not null default '[]'::jsonb,
  add column if not exists deadline_snapshot jsonb default '{}'::jsonb,
  add column if not exists next_steps jsonb not null default '[]'::jsonb,
  add column if not exists offer_type text,
  add column if not exists offer_received_at timestamptz,
  add column if not exists offer_letter_file_url text,
  add column if not exists admin_override boolean not null default false,
  add column if not exists override_reason text,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

alter table public.documents
  add column if not exists quality_flag text,
  add column if not exists quality_flags jsonb not null default '[]'::jsonb,
  add column if not exists mime_type text,
  add column if not exists review_notes text,
  add column if not exists rejection_reason text,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

alter table public.notes
  add column if not exists student_user_id uuid references auth.users(id) on delete cascade,
  add column if not exists author_user_id uuid references auth.users(id) on delete cascade,
  add column if not exists author_role text,
  add column if not exists note text,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

create index if not exists idx_profiles_user_id on public.profiles(user_id);
create index if not exists idx_profiles_role on public.profiles(role);
create index if not exists idx_profiles_email on public.profiles(lower(email));
create index if not exists idx_profiles_phone on public.profiles(phone);
create index if not exists idx_profiles_assigned_counselor on public.profiles(assigned_counselor_id);
create index if not exists idx_profiles_preferred_intake_year on public.profiles(preferred_intake_year);
create index if not exists idx_profiles_needs_rematch on public.profiles(needs_rematch);
create index if not exists idx_profiles_role_created_at_desc on public.profiles(role, created_at desc);
create index if not exists idx_profiles_assigned_counselor_role_created_at_desc on public.profiles(assigned_counselor_id, role, created_at desc);
create index if not exists idx_profiles_created_at_desc on public.profiles(created_at desc);
create index if not exists idx_universities_country on public.universities(country);
create index if not exists idx_universities_country_ranking on public.universities(country, ranking asc);
create index if not exists idx_universities_name_trgm on public.universities using gin(name gin_trgm_ops);
create index if not exists idx_university_stats_university_id on public.university_stats(university_id);
create index if not exists idx_programs_university_id on public.programs(university_id);
create index if not exists idx_programs_degree_level on public.programs(degree_level);
create index if not exists idx_programs_application_deadline on public.programs(application_deadline);
create index if not exists idx_programs_is_active on public.programs(is_active);
create index if not exists idx_programs_university_degree_name on public.programs(university_id, degree_level, name);
create index if not exists idx_programs_degree_active_deadline on public.programs(degree_level, is_active, application_deadline);
create index if not exists idx_programs_name_trgm on public.programs using gin(name gin_trgm_ops);
create index if not exists idx_programs_subject_area_trgm on public.programs using gin(subject_area gin_trgm_ops);
create index if not exists idx_scholarships_university_id on public.scholarships(university_id);
create index if not exists idx_scholarships_active_featured_deadline on public.scholarships(is_active, is_featured desc, deadline asc);
create index if not exists idx_scholarships_active_university_deadline on public.scholarships(is_active, university_id, deadline asc);
create index if not exists idx_scholarships_active_funding_deadline on public.scholarships(is_active, funding_type, deadline asc);
create index if not exists idx_scholarships_active_application_type_deadline on public.scholarships(is_active, application_type, deadline asc);
create index if not exists idx_blog_posts_slug on public.blog_posts(slug);
create index if not exists idx_blog_posts_published on public.blog_posts(published);
create index if not exists idx_blog_posts_published_created_at_desc on public.blog_posts(published, created_at desc);
create index if not exists idx_blog_posts_published_category_created_at_desc on public.blog_posts(published, category, created_at desc);
create index if not exists idx_applications_user_id on public.applications(user_id);
create index if not exists idx_applications_program_id on public.applications(program_id);
create index if not exists idx_applications_status on public.applications(status);
create unique index if not exists idx_applications_unique_user_program on public.applications(user_id, program_id);
create index if not exists idx_applications_counselor_id on public.applications(counselor_id);
create index if not exists idx_applications_user_created_at_desc on public.applications(user_id, created_at desc);
create index if not exists idx_applications_user_status_created_at_desc on public.applications(user_id, status, created_at desc);
create index if not exists idx_applications_counselor_created_at_desc on public.applications(counselor_id, created_at desc);
create index if not exists idx_applications_counselor_status_created_at_desc on public.applications(counselor_id, status, created_at desc);
create index if not exists idx_applications_status_created_at_desc on public.applications(status, created_at desc);
create index if not exists idx_documents_user_id on public.documents(user_id);
create index if not exists idx_documents_status on public.documents(status);
create index if not exists idx_documents_user_created_at_desc on public.documents(user_id, created_at desc);
create index if not exists idx_documents_user_status_created_at_desc on public.documents(user_id, status, created_at desc);
create index if not exists idx_audit_logs_user_id on public.audit_logs(user_id);
create index if not exists idx_audit_logs_actor_user_id on public.audit_logs(actor_user_id);
create index if not exists idx_audit_logs_action on public.audit_logs(action);
create index if not exists idx_audit_logs_user_created_at_desc on public.audit_logs(user_id, created_at desc);
create index if not exists idx_audit_logs_actor_created_at_desc on public.audit_logs(actor_user_id, created_at desc);
create index if not exists idx_notes_student_user_id on public.notes(student_user_id);
create index if not exists idx_notes_author_user_id on public.notes(author_user_id);
create index if not exists idx_notes_student_created_at_desc on public.notes(student_user_id, created_at desc);

drop trigger if exists trg_profiles_updated_at on public.profiles;
create trigger trg_profiles_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

drop trigger if exists trg_countries_updated_at on public.countries;
create trigger trg_countries_updated_at
before update on public.countries
for each row execute function public.set_updated_at();

drop trigger if exists trg_universities_updated_at on public.universities;
create trigger trg_universities_updated_at
before update on public.universities
for each row execute function public.set_updated_at();

drop trigger if exists trg_university_stats_updated_at on public.university_stats;
create trigger trg_university_stats_updated_at
before update on public.university_stats
for each row execute function public.set_updated_at();

drop trigger if exists trg_programs_updated_at on public.programs;
create trigger trg_programs_updated_at
before update on public.programs
for each row execute function public.set_updated_at();

drop trigger if exists trg_scholarships_updated_at on public.scholarships;
create trigger trg_scholarships_updated_at
before update on public.scholarships
for each row execute function public.set_updated_at();

drop trigger if exists trg_blog_posts_updated_at on public.blog_posts;
create trigger trg_blog_posts_updated_at
before update on public.blog_posts
for each row execute function public.set_updated_at();

drop trigger if exists trg_applications_updated_at on public.applications;
create trigger trg_applications_updated_at
before update on public.applications
for each row execute function public.set_updated_at();

drop trigger if exists trg_documents_updated_at on public.documents;
create trigger trg_documents_updated_at
before update on public.documents
for each row execute function public.set_updated_at();

drop trigger if exists trg_notes_updated_at on public.notes;
create trigger trg_notes_updated_at
before update on public.notes
for each row execute function public.set_updated_at();

alter table public.profiles enable row level security;
alter table public.countries enable row level security;
alter table public.universities enable row level security;
alter table public.university_stats enable row level security;
alter table public.programs enable row level security;
alter table public.scholarships enable row level security;
alter table public.blog_posts enable row level security;
alter table public.applications enable row level security;
alter table public.documents enable row level security;
alter table public.audit_logs enable row level security;
alter table public.notes enable row level security;

create or replace function public.is_admin()
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (
    select 1
    from public.profiles
    where user_id = auth.uid()
      and role = 'admin'
  );
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to authenticated;

create or replace function public.is_counselor()
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (
    select 1
    from public.profiles
    where user_id = auth.uid()
      and role = 'counselor'
  );
$$;

revoke all on function public.is_counselor() from public;
grant execute on function public.is_counselor() to authenticated;

create or replace function public.is_assigned_counselor(student_user uuid)
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (
    select 1
    from public.profiles
    where user_id = student_user
      and assigned_counselor_id = auth.uid()
      and role = 'student'
  );
$$;

revoke all on function public.is_assigned_counselor(uuid) from public;
grant execute on function public.is_assigned_counselor(uuid) to authenticated;

do $$
declare
  policy_row record;
begin
  for policy_row in
    select schemaname, tablename, policyname
    from pg_policies
    where schemaname = 'public'
      and tablename in (
        'profiles',
        'countries',
        'universities',
        'university_stats',
        'programs',
        'scholarships',
        'blog_posts',
        'applications',
        'documents'
        ,'audit_logs'
        ,'notes'
      )
  loop
    execute format(
      'drop policy if exists %I on public.%I',
      policy_row.policyname,
      policy_row.tablename
    );
  end loop;
end
$$;

create policy "Profiles select own or admin"
on public.profiles
for select
to authenticated
using (
  auth.uid() = user_id
  or public.is_admin()
  or (
    public.is_counselor()
    and role = 'student'
    and assigned_counselor_id = auth.uid()
  )
);

create policy "Profiles insert own or admin"
on public.profiles
for insert
to authenticated
with check (auth.uid() = user_id or public.is_admin());

create policy "Profiles update own or admin"
on public.profiles
for update
to authenticated
using (auth.uid() = user_id or public.is_admin())
with check (auth.uid() = user_id or public.is_admin());

create policy "Profiles delete admin only"
on public.profiles
for delete
to authenticated
using (public.is_admin());

create policy "Public read countries"
on public.countries
for select
to anon, authenticated
using (true);

create policy "Public read universities"
on public.universities
for select
to anon, authenticated
using (true);

create policy "Public read university stats"
on public.university_stats
for select
to anon, authenticated
using (true);

create policy "Public read programs"
on public.programs
for select
to anon, authenticated
using (true);

create policy "Public read scholarships"
on public.scholarships
for select
to anon, authenticated
using (true);

create policy "Public read blog posts"
on public.blog_posts
for select
to anon, authenticated
using (published = true or public.is_admin());

create policy "Admin manage countries"
on public.countries
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy "Admin manage universities"
on public.universities
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy "Admin manage university stats"
on public.university_stats
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy "Admin manage programs"
on public.programs
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy "Admin manage scholarships"
on public.scholarships
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy "Admin manage blog posts"
on public.blog_posts
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy "Applications select own or admin"
on public.applications
for select
to authenticated
using (auth.uid() = user_id or public.is_admin() or (public.is_counselor() and counselor_id = auth.uid()));

create policy "Applications insert own or admin"
on public.applications
for insert
to authenticated
with check (auth.uid() = user_id or public.is_admin());

create policy "Applications update own or admin"
on public.applications
for update
to authenticated
using (auth.uid() = user_id or public.is_admin() or (public.is_counselor() and counselor_id = auth.uid()))
with check (auth.uid() = user_id or public.is_admin() or (public.is_counselor() and counselor_id = auth.uid()));

create policy "Applications delete own or admin"
on public.applications
for delete
to authenticated
using (auth.uid() = user_id or public.is_admin());

create policy "Documents select own or admin"
on public.documents
for select
to authenticated
using (auth.uid() = user_id or public.is_admin() or (public.is_counselor() and public.is_assigned_counselor(user_id)));

create policy "Documents insert own or admin"
on public.documents
for insert
to authenticated
with check (auth.uid() = user_id or public.is_admin());

create policy "Documents update own or admin"
on public.documents
for update
to authenticated
using (auth.uid() = user_id or public.is_admin())
with check (auth.uid() = user_id or public.is_admin());

create policy "Documents delete own or admin"
on public.documents
for delete
to authenticated
using (auth.uid() = user_id or public.is_admin());

create policy "Audit logs select own or admin"
on public.audit_logs
for select
to authenticated
using (auth.uid() = user_id or public.is_admin() or auth.uid() = actor_user_id);

create policy "Audit logs insert own or admin"
on public.audit_logs
for insert
to authenticated
with check (auth.uid() = actor_user_id or public.is_admin());

create policy "Notes select staff"
on public.notes
for select
to authenticated
using (
  public.is_admin()
  or auth.uid() = author_user_id
  or (public.is_counselor() and public.is_assigned_counselor(student_user_id))
);

create policy "Notes insert staff"
on public.notes
for insert
to authenticated
with check (
  public.is_admin()
  or (
    public.is_counselor()
    and auth.uid() = author_user_id
    and public.is_assigned_counselor(student_user_id)
  )
);

commit;
