-- StudyGlobal complete Supabase schema bootstrap
-- Run this in the Supabase SQL editor with a service-role connection.
-- It is intended to be idempotent and to cover the tables/policies the app code expects.

begin;

create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.profiles (
  id bigint generated by default as identity primary key,
  user_id uuid not null unique references auth.users(id) on delete cascade,
  name text not null,
  email text not null,
  phone text,
  nationality text,
  preferred_country text,
  education_level text,
  gpa numeric(3,2),
  gpa_scale numeric(4,2),
  academic_system text,
  english_score numeric(4,1),
  english_test_type text,
  medium_of_instruction text,
  last_education_year integer,
  study_level text,
  preferred_subject text,
  budget_min integer,
  budget_max integer,
  intake text,
  role text not null default 'student' check (role in ('student', 'admin', 'counselor', 'editor')),
  profile_completion integer not null default 0 check (profile_completion between 0 and 100),
  profile_status text not null default 'incomplete' check (profile_status in ('complete', 'incomplete')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.countries (
  id bigint generated by default as identity primary key,
  name text not null unique,
  description text,
  flag_emoji text,
  image_url text,
  university_count integer default 0,
  avg_tuition integer,
  min_gpa_required numeric(3,2),
  gpa_tolerance numeric(3,2),
  english_test_required boolean default true,
  english_medium_waiver_allowed boolean default true,
  max_gap_years integer,
  gap_risk_threshold integer,
  budget_tolerance_pct numeric(4,2),
  doc_requirements jsonb default '[]'::jsonb,
  requirements jsonb default '{}'::jsonb,
  intl_students text,
  popular_cities text,
  highlights text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.universities (
  id bigint generated by default as identity primary key,
  name text not null unique,
  country text not null,
  description text,
  ranking integer,
  logo_url text,
  tuition_min integer,
  tuition_max integer,
  acceptance_rate numeric(5,2),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.programs (
  id bigint generated by default as identity primary key,
  university_id bigint not null references public.universities(id) on delete cascade,
  name text not null,
  degree_level text not null,
  duration text,
  tuition_fee integer,
  subject_area text,
  related_subjects jsonb default '[]'::jsonb,
  min_gpa_required numeric(3,2),
  min_english_score numeric(4,1),
  english_test_required boolean,
  intake_periods text,
  scholarship_available boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.scholarships (
  id bigint generated by default as identity primary key,
  name text not null,
  university_id bigint references public.universities(id) on delete cascade,
  program_id bigint references public.programs(id) on delete set null,
  funding_type text,
  amount integer,
  description text,
  eligibility text,
  min_gpa_required numeric(3,2),
  deadline timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.blog_posts (
  id bigint generated by default as identity primary key,
  title text not null,
  slug text not null unique,
  excerpt text,
  content text,
  image_url text,
  category text,
  published boolean not null default false,
  author_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.applications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  program_id bigint not null references public.programs(id) on delete cascade,
  counselor_id uuid references auth.users(id) on delete set null,
  intake text,
  notes text,
  eligibility_snapshot jsonb default '{}'::jsonb,
  admin_override boolean not null default false,
  override_reason text,
  status text not null default 'draft' check (
    status in ('draft', 'submitted', 'under_review', 'accepted', 'rejected', 'visa_processing')
  ),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.documents (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  document_type text not null,
  file_name text not null,
  file_url text not null,
  file_size bigint,
  mime_type text,
  review_notes text,
  rejection_reason text,
  status text not null default 'pending' check (status in ('pending', 'verified', 'rejected')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  actor_user_id uuid references auth.users(id) on delete set null,
  action text not null,
  entity_type text not null,
  entity_id text,
  details jsonb default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.profiles
  add column if not exists gpa_scale numeric(4,2),
  add column if not exists academic_system text,
  add column if not exists medium_of_instruction text,
  add column if not exists last_education_year integer,
  add column if not exists profile_status text not null default 'incomplete',
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

alter table public.countries
  add column if not exists min_gpa_required numeric(3,2),
  add column if not exists gpa_tolerance numeric(3,2),
  add column if not exists english_test_required boolean default true,
  add column if not exists english_medium_waiver_allowed boolean default true,
  add column if not exists max_gap_years integer,
  add column if not exists gap_risk_threshold integer,
  add column if not exists budget_tolerance_pct numeric(4,2),
  add column if not exists doc_requirements jsonb default '[]'::jsonb,
  add column if not exists requirements jsonb default '{}'::jsonb,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

alter table public.universities
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

alter table public.programs
  add column if not exists subject_area text,
  add column if not exists related_subjects jsonb default '[]'::jsonb,
  add column if not exists english_test_required boolean,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

alter table public.scholarships
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

alter table public.blog_posts
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

alter table public.applications
  add column if not exists eligibility_snapshot jsonb default '{}'::jsonb,
  add column if not exists admin_override boolean not null default false,
  add column if not exists override_reason text,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

alter table public.documents
  add column if not exists mime_type text,
  add column if not exists review_notes text,
  add column if not exists rejection_reason text,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

create index if not exists idx_profiles_user_id on public.profiles(user_id);
create index if not exists idx_profiles_role on public.profiles(role);
create index if not exists idx_universities_country on public.universities(country);
create index if not exists idx_programs_university_id on public.programs(university_id);
create index if not exists idx_programs_degree_level on public.programs(degree_level);
create index if not exists idx_scholarships_university_id on public.scholarships(university_id);
create index if not exists idx_blog_posts_slug on public.blog_posts(slug);
create index if not exists idx_blog_posts_published on public.blog_posts(published);
create index if not exists idx_applications_user_id on public.applications(user_id);
create index if not exists idx_applications_program_id on public.applications(program_id);
create index if not exists idx_applications_status on public.applications(status);
create index if not exists idx_documents_user_id on public.documents(user_id);
create index if not exists idx_documents_status on public.documents(status);
create index if not exists idx_audit_logs_user_id on public.audit_logs(user_id);
create index if not exists idx_audit_logs_actor_user_id on public.audit_logs(actor_user_id);
create index if not exists idx_audit_logs_action on public.audit_logs(action);

drop trigger if exists trg_profiles_updated_at on public.profiles;
create trigger trg_profiles_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

drop trigger if exists trg_countries_updated_at on public.countries;
create trigger trg_countries_updated_at
before update on public.countries
for each row execute function public.set_updated_at();

drop trigger if exists trg_universities_updated_at on public.universities;
create trigger trg_universities_updated_at
before update on public.universities
for each row execute function public.set_updated_at();

drop trigger if exists trg_programs_updated_at on public.programs;
create trigger trg_programs_updated_at
before update on public.programs
for each row execute function public.set_updated_at();

drop trigger if exists trg_scholarships_updated_at on public.scholarships;
create trigger trg_scholarships_updated_at
before update on public.scholarships
for each row execute function public.set_updated_at();

drop trigger if exists trg_blog_posts_updated_at on public.blog_posts;
create trigger trg_blog_posts_updated_at
before update on public.blog_posts
for each row execute function public.set_updated_at();

drop trigger if exists trg_applications_updated_at on public.applications;
create trigger trg_applications_updated_at
before update on public.applications
for each row execute function public.set_updated_at();

drop trigger if exists trg_documents_updated_at on public.documents;
create trigger trg_documents_updated_at
before update on public.documents
for each row execute function public.set_updated_at();

alter table public.profiles enable row level security;
alter table public.countries enable row level security;
alter table public.universities enable row level security;
alter table public.programs enable row level security;
alter table public.scholarships enable row level security;
alter table public.blog_posts enable row level security;
alter table public.applications enable row level security;
alter table public.documents enable row level security;
alter table public.audit_logs enable row level security;

create or replace function public.is_admin()
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (
    select 1
    from public.profiles
    where user_id = auth.uid()
      and role = 'admin'
  );
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to authenticated;

do $$
declare
  policy_row record;
begin
  for policy_row in
    select schemaname, tablename, policyname
    from pg_policies
    where schemaname = 'public'
      and tablename in (
        'profiles',
        'countries',
        'universities',
        'programs',
        'scholarships',
        'blog_posts',
        'applications',
        'documents'
        ,'audit_logs'
      )
  loop
    execute format(
      'drop policy if exists %I on public.%I',
      policy_row.policyname,
      policy_row.tablename
    );
  end loop;
end
$$;

create policy "Profiles select own or admin"
on public.profiles
for select
to authenticated
using (auth.uid() = user_id or public.is_admin());

create policy "Profiles insert own or admin"
on public.profiles
for insert
to authenticated
with check (auth.uid() = user_id or public.is_admin());

create policy "Profiles update own or admin"
on public.profiles
for update
to authenticated
using (auth.uid() = user_id or public.is_admin())
with check (auth.uid() = user_id or public.is_admin());

create policy "Profiles delete admin only"
on public.profiles
for delete
to authenticated
using (public.is_admin());

create policy "Public read countries"
on public.countries
for select
to anon, authenticated
using (true);

create policy "Public read universities"
on public.universities
for select
to anon, authenticated
using (true);

create policy "Public read programs"
on public.programs
for select
to anon, authenticated
using (true);

create policy "Public read scholarships"
on public.scholarships
for select
to anon, authenticated
using (true);

create policy "Public read blog posts"
on public.blog_posts
for select
to anon, authenticated
using (published = true or public.is_admin());

create policy "Admin manage countries"
on public.countries
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy "Admin manage universities"
on public.universities
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy "Admin manage programs"
on public.programs
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy "Admin manage scholarships"
on public.scholarships
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy "Admin manage blog posts"
on public.blog_posts
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy "Applications select own or admin"
on public.applications
for select
to authenticated
using (auth.uid() = user_id or public.is_admin());

create policy "Applications insert own or admin"
on public.applications
for insert
to authenticated
with check (auth.uid() = user_id or public.is_admin());

create policy "Applications update own or admin"
on public.applications
for update
to authenticated
using (auth.uid() = user_id or public.is_admin())
with check (auth.uid() = user_id or public.is_admin());

create policy "Applications delete own or admin"
on public.applications
for delete
to authenticated
using (auth.uid() = user_id or public.is_admin());

create policy "Documents select own or admin"
on public.documents
for select
to authenticated
using (auth.uid() = user_id or public.is_admin());

create policy "Documents insert own or admin"
on public.documents
for insert
to authenticated
with check (auth.uid() = user_id or public.is_admin());

create policy "Documents update own or admin"
on public.documents
for update
to authenticated
using (auth.uid() = user_id or public.is_admin())
with check (auth.uid() = user_id or public.is_admin());

create policy "Documents delete own or admin"
on public.documents
for delete
to authenticated
using (auth.uid() = user_id or public.is_admin());

create policy "Audit logs select own or admin"
on public.audit_logs
for select
to authenticated
using (auth.uid() = user_id or public.is_admin() or auth.uid() = actor_user_id);

create policy "Audit logs insert own or admin"
on public.audit_logs
for insert
to authenticated
with check (auth.uid() = actor_user_id or public.is_admin());

commit;
